**Matrix Multiplication**
# We will use tf.matmul() method
**Rules:**


1.   Inner dimensions must match (m,n)@(n,p)
for eg,


*   (5,7)@(8,9) it will not work because n are different
*   (5,8)@(8,9) it will work because inner diemnsions are same



2.   The result matrix has the shape of outer dimensions means
A (m,n)
B (N,P)
So result has (m,p) eg, (4,7)@(7,5) ->(4,5)


In [1]:
import tensorflow as tf
import numpy as np

In [10]:
tensor_A=tf.constant([[1,2],[3,4],[4,5]],dtype=tf.int32)
tensor_B=tf.constant([[5,6],[7,8]],dtype=tf.int32)
print("Shape of A",tensor_A.shape)
print("Shape of B",tensor_B.shape)

Shape of A (3, 2)
Shape of B (2, 2)


In [11]:
tensor_C=tf.matmul(tensor_A,tensor_B)
print(tensor_C)
print('Shape of tensor_C',tensor_C.shape)

tf.Tensor(
[[19 22]
 [43 50]
 [55 64]], shape=(3, 2), dtype=int32)
Shape of tensor_C (3, 2)


In [13]:
X=tf.constant(  [
                [1.,0.,-1.],
                [2.,3.,1.]
                ]
              ,dtype=tf.float32)
X


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  0., -1.],
       [ 2.,  3.,  1.]], dtype=float32)>

In [14]:
Y=tf.constant([
    [4.],
    [5.],
    [6.],
],
dtype=tf.float32)
Y

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>

In [17]:
print("X-Shape", X.shape)
print("Y-Shape", Y.shape)

X-Shape (2, 3)
Y-Shape (3, 1)


In [18]:
Z=tf.matmul(X,Y)
Z

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-2.],
       [29.]], dtype=float32)>

In [20]:
print(f'X-Shape : {X.shape} ,Y-shape : {Y.shape}, Z-shape : {Z.shape}')
print(X.numpy())
print(Y.numpy())
print(Z.numpy())

X-Shape : (2, 3) ,Y-shape : (3, 1), Z-shape : (2, 1)
[[ 1.  0. -1.]
 [ 2.  3.  1.]]
[[4.]
 [5.]
 [6.]]
[[-2.]
 [29.]]


Transpose:
Transpose swaps axes. For 2D matrix shape(m,n) become (n,m)

In [22]:
tensor_one=tf.constant([
    [[1,2],[2,3]],
    [[4,5],[6,7]],

],dtype=tf.int32)
print(tensor_one)
print('Shape of tensor_one : \t',tensor_one.shape)

tf.Tensor(
[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]], shape=(2, 2, 2), dtype=int32)
Shape of tensor_one : 	 (2, 2, 2)


In [24]:
tensor_one_transpose=tf.transpose(tensor_one)
print(tensor_one_transpose)
print("Shape of tensor_one_transpose",tensor_one_transpose.shape)

tf.Tensor(
[[[1 4]
  [2 6]]

 [[2 5]
  [3 7]]], shape=(2, 2, 2), dtype=int32)
Shape of tensor_one_transpose (2, 2, 2)


In [26]:
# 3D Transpose with explicits axis permutation
tensor_two=tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
],dtype=tf.int32)
print(tensor_two)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [29]:
#swap first and last axex (0,1,2) -> (0,2,1)
t2_transpose=tf.transpose(tensor_two,perm=[0,2,1])
print(t2_transpose)
print("Shape of t2_transpose",t2_transpose.shape)
print("Shape of tensor_two",tensor_two.shape)

tf.Tensor(
[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]], shape=(2, 2, 2), dtype=int32)
Shape of t2_transpose (2, 2, 2)
Shape of tensor_two (2, 2, 2)


In [ ]:
# Reshape


# Reshape
# tf.reshape(tensor,new_shape)
#change the shape without changing the data
**Rule**
The total number of elements must stay the same

In [31]:
tensor=tf.constant([
    [1,2,3],
    [4,5,6]
],dtype=tf.int32)
print(tensor)
print("Shape of tensor",tensor.shape)
print("Number of elements are:",tf.size(tensor).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape of tensor (2, 3)
Number of elements are: 6


In [33]:
tensor_r1=tf.reshape(tensor,shape=(3,2))
print(tensor_r1)
print("Shape of tensor_r1",tensor_r1.shape)
print("Number of elements are: ",tf.size(tensor_r1).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor_r1 (3, 2)
Number of elements are:  6


In [34]:
tensor_r2=tf.reshape(tensor,shape=(3,2))
print(tensor_r2)
print("Shape of tensor",tensor_r2.shape)
print("Number of elements are: ",tf.size(tensor_r2).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor (3, 2)
Number of elements are:  6


In [36]:
tensor_r3=tf.reshape(tensor,shape=(3,2))
print(tensor_r3)
print("Shape of tensor",tensor_r3.shape)
print("Number of elements are: ",tf.size(tensor_r3).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor (3, 2)
Number of elements are:  6


In [37]:
# infer dimension
tensor_r4=tf.reshape(tensor,shape=(-1,2))
print(tensor_r4)
print("Shape of tensor",tensor_r4.shape)
print("Number of elements are: ",tf.size(tensor_r4).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor (3, 2)
Number of elements are:  6


In [38]:
tensor_r4=tf.reshape(tensor,shape=(-1,3))
print(tensor_r4)
print("Shape of tensor",tensor_r4.shape)
print("Number of elements are: ",tf.size(tensor_r4).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape of tensor (2, 3)
Number of elements are:  6


In [40]:
#TODO: Reshape (2,6) -> (3,4) and (1,12)
tensor_given = tf.constant([[1,2,3,4,5,6],
               [7,8,9,10,11,12]],dtype=tf.int32)
print(tensor_given)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)


In [41]:
tensor_A = tf.constant([[1, 2], [3, 4], [4, 5]], dtype=tf.int32)
tensor_B = tf.constant([[5, 6], [7, 8]], dtype=tf.int32)

print("Shape of A:", tensor_A.shape)
print("Shape of B:", tensor_B.shape)

Shape of A: (3, 2)
Shape of B: (2, 2)


In [42]:
tensor_C = tf.matmul(tensor_A, tensor_B)
print(tensor_C)
print("Shape of tensor_C:", tensor_C.shape)

tf.Tensor(
[[19 22]
 [43 50]
 [55 64]], shape=(3, 2), dtype=int32)
Shape of tensor_C: (3, 2)
