We are going to start TensorFlow Basics HERE

In [1]:
import tensorflow as tf

In [5]:
print(tf.__version__)

2.19.0


In [4]:
#Creatint Tensor with constant
#function here that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [9]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
vector.ndim

1

In [11]:
matrix=tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [12]:
matrix.ndim

2

In [13]:
second_matrix=tf.constant([[5,7],
                          [3,8],
                          [3,9],
                          [4,2],
                          [8,6]])

In [14]:
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [15]:
second_matrix.ndim

2

In [16]:
third_matrix=tf.constant(
     [
    [[1,2,3],
    [2,4,5]],
    [[7,9,3],
    [10,4,5]],
    [[11,2,3],
    [2,4,15]],
            ])
third_matrix


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5]],

       [[ 7,  9,  3],
        [10,  4,  5]],

       [[11,  2,  3],
        [ 2,  4, 15]]], dtype=int32)>

In [17]:
third_matrix.ndim

3

In [26]:
second_matrix = tf.constant([
    [5.0, 6.0, 7.0, 3.0],
    [3.48, 8.25, 0.0, 0.0],
    [3.11, 9.23, 0.0, 0.0],
    [4.34, 2.34, 0.0, 0.0],
    [8.4, 6.23, 0.0, 0.0]
], dtype=tf.float32)

print(second_matrix)


tf.Tensor(
[[5.   6.   7.   3.  ]
 [3.48 8.25 0.   0.  ]
 [3.11 9.23 0.   0.  ]
 [4.34 2.34 0.   0.  ]
 [8.4  6.23 0.   0.  ]], shape=(5, 4), dtype=float32)


In [33]:
second_matrix.ndim

2

In [27]:
#single numbe that means scalar
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [28]:
# a number with direction
vector=tf.constant([10,10,])

In [30]:
# 2D array of numbers
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [31]:
#Tensor : an n-dimensional array of number
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [35]:
# Find the shape,rank ans size of tensor
print("Scalar Information")
print("Shape:",scalar.shape)
print("Diemnsion:",scalar.ndim)
print("Rank:",tf.rank(scalar).numpy())
print("Size:",tf.size(scalar))


Scalar Information
Shape: ()
Diemnsion: 0
Rank: 0
Size: tf.Tensor(1, shape=(), dtype=int32)


In [36]:
print("Vector Information")
print("Shape:",vector.shape)
print("Diemnsion:",vector.ndim)
print("Rank:",tf.rank(vector).numpy())
print("Size:",tf.size(vector))

Vector Information
Shape: (2,)
Diemnsion: 1
Rank: 1
Size: tf.Tensor(2, shape=(), dtype=int32)


In [37]:
print("Matrix Information")
print("Shape:",matrix.shape)
print("Diemnsion:",matrix.ndim)
print("Rank:",tf.rank(matrix).numpy())
print("Size:",tf.size(matrix))

Matrix Information
Shape: (2, 2)
Diemnsion: 2
Rank: 2
Size: tf.Tensor(4, shape=(), dtype=int32)


In [38]:
print("Tensor Information")
print("Shape:",tensor.shape)
print("Diemnsion:",tensor.ndim)
print("Rank:",tf.rank(tensor).numpy())
print("Size:",tf.size(tensor))

Tensor Information
Shape: (2, 2, 2)
Diemnsion: 3
Rank: 3
Size: tf.Tensor(8, shape=(), dtype=int32)


In [39]:
# creating tensor using variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [40]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [41]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [43]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [44]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [45]:
# unchangeable_tensor[0].assign(12)
# unchangeable_tensor
# this will be an error because you can't vhnage constant tensor. they are immutable i.e unchangeable

In [47]:
# Random tensors
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [48]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[4.2023897e-02, 3.1358874e-01, 6.4472365e-01, ..., 2.7106416e-01,
        3.1700158e-01, 9.9030054e-01],
       [8.1233919e-01, 1.5942836e-01, 1.4678812e-01, ..., 2.2812951e-01,
        9.8770583e-01, 4.6208811e-01],
       [5.4922628e-01, 3.7075007e-01, 7.3653162e-01, ..., 4.8943877e-01,
        4.8931789e-01, 2.2054768e-01],
       ...,
       [4.2790198e-01, 3.2380259e-01, 1.2002516e-01, ..., 2.1576631e-01,
        3.6287069e-01, 5.9745681e-01],
       [3.1556487e-01, 4.7436059e-01, 3.6242449e-01, ..., 8.5318089e-04,
        9.8761916e-01, 9.9475229e-01],
       [2.9343820e-01, 4.2068005e-02, 1.9726312e-01, ..., 2.5504971e-01,
        8.6427546e-01, 9.8463249e-01]], dtype=float32)>

In [51]:
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [53]:
#creating tensors using zeroes
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [55]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [56]:
#tensors for all ones
tensor_ones=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [60]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [61]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [63]:
print("Tensor Information")
print("Shape:",tensor.shape)
print("Diemnsion:",tensor.ndim)
print("Rank:",tf.rank(tensor).numpy())
print("Size:",tf.size(tensor))
print("DataType of elements: ",tensor_numpy.dtype)
print("Elements along axis 0:",tensor_numpy.shape[0])
print("Elements along axis 1:",tensor_numpy.shape[1])
print("Elements along axis 2:",tensor_numpy.shape[2])
print("Total number of elements: \t",tf.size(tensor_numpy).numpy())

Tensor Information
Shape: (2, 2, 2)
Diemnsion: 3
Rank: 3
Size: tf.Tensor(8, shape=(), dtype=int32)
DataType of elements:  <dtype: 'int16'>
Elements along axis 0: 2
Elements along axis 1: 3
Elements along axis 2: 4
Total number of elements: 	 24


In [65]:
#working with items of each dimension
# first three elements of each dimension
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [66]:
#first two element of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

** Arthmetic Operations with Tensors **


*   Add
*   Sub

*   Multi
*   Div





In [68]:
tensor_one=tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [73]:
#tensor_one+15
tf.add(tensor_one,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [75]:
#tensor_one-5
tf.subtract(tensor_one,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [76]:
#tensor_one*2
tf.multiply(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [ 4, 10]], dtype=int32)>

In [77]:
#tensor_one/2
tf.divide(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [79]:
tensor_new=tf.square(tensor_one)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [ ]:
tf.sqrt(tensor_new)

In [82]:
second_mtrix=tf.constant([[8,16],[64,8.25],
                         [625,9.23],
                         [125,2.34],
                         [169,144]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[5.   6.   7.   3.  ]
 [3.48 8.25 0.   0.  ]
 [3.11 9.23 0.   0.  ]
 [4.34 2.34 0.   0.  ]
 [8.4  6.23 0.   0.  ]], shape=(5, 4), dtype=float32)


In [83]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[2.236068 , 2.4494898, 2.6457512, 1.7320508],
       [1.8654758, 2.8722813, 0.       , 0.       ],
       [1.7635192, 3.0380914, 0.       , 0.       ],
       [2.0832667, 1.5297059, 0.       , 0.       ],
       [2.8982754, 2.4959967, 0.       , 0.       ]], dtype=float32)>

**Exercise**
Create two tensors with random values between 0 and 1, shape is [6,300]
**Find out the details:**


*   Number of elements
*   Size


*   Rank
*   Shape





In [84]:
import tensorflow as tf

In [85]:
tensor_a = tf.random.uniform(shape=(6, 300), minval=0, maxval=1)
tensor_b = tf.random.uniform(shape=(6, 300), minval=0, maxval=1)

In [86]:
tensor_a_numpy = tensor_a.numpy()
tensor_b_numpy = tensor_b.numpy()

In [87]:
print("Tensor A Information")
print("Shape:", tensor_a.shape)
print("Dimension:", tensor_a.ndim)
print("Rank:", tf.rank(tensor_a).numpy())
print("Size:", tf.size(tensor_a).numpy())
print("Data Type of elements:", tensor_a_numpy.dtype)
print("Elements along axis 0:", tensor_a_numpy.shape[0])
print("Elements along axis 1:", tensor_a_numpy.shape[1])
print("Total number of elements:", tf.size(tensor_a_numpy).numpy())
print()

Tensor A Information
Shape: (6, 300)
Dimension: 2
Rank: 2
Size: 1800
Data Type of elements: float32
Elements along axis 0: 6
Elements along axis 1: 300
Total number of elements: 1800



In [88]:
print("Tensor B Information")
print("Shape:", tensor_b.shape)
print("Dimension:", tensor_b.ndim)
print("Rank:", tf.rank(tensor_b).numpy())
print("Size:", tf.size(tensor_b).numpy())
print("Data Type of elements:", tensor_b_numpy.dtype)
print("Elements along axis 0:", tensor_b_numpy.shape[0])
print("Elements along axis 1:", tensor_b_numpy.shape[1])
print("Total number of elements:", tf.size(tensor_b_numpy).numpy())

Tensor B Information
Shape: (6, 300)
Dimension: 2
Rank: 2
Size: 1800
Data Type of elements: float32
Elements along axis 0: 6
Elements along axis 1: 300
Total number of elements: 1800
