In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('students.xlsx')
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92


In [3]:
marks=df['Marks'].to_numpy()
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92]


In [5]:
print('Highest marks ',np.max(marks))

Highest marks  92


In [7]:
print('Lowest marks ',np.min(marks))

Lowest marks  78


In [8]:
print('Average Marks ',np.mean(marks))

Average Marks  86.25


## .iloc: Label Based
## .iloc: index based

In [11]:
#Example 1 : .loc label based

print('original dataframe')
print(df)
print('Location : Label Based')
print(df.loc[2,['Name','Marks']])

original dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
Location : Label Based
Name     Bob
Marks     78
Name: 2, dtype: object


In [12]:
#Example 2 : .iloc index based

print('original dataframe')
print(df)
print('Location : Index Based')
print(df.iloc[2,[1,2]])

original dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
Location : Index Based
Age      21
Marks    78
Name: 2, dtype: object


# Axis in Numpy : Axis 0 : vertical direction: works column wise
    1.Axis 0: vertical direction: works column-wise
    2.Axis 1: horizontal direction: works rows-wise

# We have two students marks in 3 subjects
# [[45,50,49],[30,45,49]

In [13]:
marks_arr=np.array([[45,50,49],[30,45,49]])
print(marks_arr)

[[45 50 49]
 [30 45 49]]


In [15]:
print('Sum down each column',np.sum(marks_arr,axis=0))

Sum down each column [75 95 98]


In [17]:
print('Sum down each row',np.sum(marks_arr,axis=1))

Sum down each row [144 124]


In [18]:
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92]


In [19]:
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92


## Find the student name who got highest marks

In [20]:
topper=df.loc[df['Marks'].idxmax(),'Name']
print(topper)

Sara


In [22]:
lastinclass=df.loc[df['Marks'].idxmin(),'Name']
print(lastinclass)

Bob


In [23]:
lastinclass=df.loc[df['Marks'].idxmax(),'Name']
print(lastinclass)

Sara


In [24]:
print('Next Example')

Next Example


In [28]:
top_index = df['Marks'].idxmax()
top_students=df.iloc[top_index,df.columns.get_loc('Name')]
print('Topper of the class is : ',top_students)

Topper of the class is :  Sara
